### ISSUE TITLE
[Feature Request] Add option to sort be natural order

### ISSUE THREAD

**Issue by c410-f3r** [Tyriar/vscode-sort-lines#10]
Can it be implemented?

**Comment by Tyriar** [comment]
What do you mean by natural order?

**Comment by c410-f3r** [comment]
Thanks for the fast reply! It is a more human-friendly sort, for example:

```
Standard sorting

img1.png
img10.png
img12.png
img2.png

Natural order sorting

img1.png
img2.png
img10.png
img12.png
```

[wikipedia](https://en.wikipedia.org/wiki/Natural_sort_order)
[stackoveflow](http://stackoverflow.com/questions/5167928/what-is-natural-ordering-when-we-talk-about-sorting)

**Comment by Tyriar** [comment]
Thanks, related to https://github.com/Tyriar/vscode-sort-lines/issues/8
