### ISSUE TITLE
Adding an Extension Suggestion

### ISSUE THREAD

**Issue by sixskys** [Tyriar/vscode-sort-lines#109]
Hey, I noticed the activity on this project died down a bit. I was wondering if you could link to my extension, as it solves a lot of the issues and requests people have.

The extension only has a single command to sort, and it receives it's options (reverse, natural, case-insensitive, etc), through a prompt. This way there doesn't need to be 10+ commands, and every possible combination is already implemented.

It also adds a lot of other options alongside the ones in this extension like: a multilevel sort (#94), a numeric and float based sort, and imo most importantly a regex based sort. 

Not sure if this is the place for promotion, but this was the biggest sort extension and mine wasn't getting to much attraction so I figured why not.

Link to the extension: https://marketplace.visualstudio.com/items?itemName=karizma.scoped-sort

Source code: https://github.com/sixskys/scoped-sort

**Comment by Tyriar** [comment]
This extension is still maintained, good luck with it
