### ISSUE TITLE
[Request] ignore last \n

### ISSUE THREAD

**Issue by jojorne** [Tyriar/vscode-sort-lines#118]
I usually drag the line numbers to select lines.
From the text below, this would select: `1\n3\n2\n`
And the cursor would be at the empty line.

From
```
A
1
3
2

B
```
Result
```
A

1
2
3
B
```
With Filter Blank Lines
```
A
1
2
3
B
```
Expected
```
A
1
2
3

B
```

**Comment by gdlx** [comment]
I came here for the exact same request.
I made a gif to show the expected behavior (when selecting the line numbers):
![sortlines](https://github.com/Tyriar/vscode-sort-lines/assets/1533042/0123d0a3-7685-43ad-84ed-69583dab85de)
