### ISSUE TITLE
[feature request] auto sort lines between comments as markers

### ISSUE THREAD

**Issue by Quantenzitrone** [Tyriar/vscode-sort-lines#125]
It would be very useful if I could automatically sort specific lines of a file on save.
I thought this could be done by wrapping something like `sortLines start` and `sortLines stop` around the lines I want to be sorted.
For example:
```nix
{
  mylist = [
    # sortLines start
    "a"
    "c"
    "b"
    # sortLines stop
  ];
}
```
for all the different types of sorting, the function names from the README could be used.

**Comment by Tyriar** [comment]
This is out of scope for the extension imo and would be better to live as a lint rule like for eslint.

**Comment by Quantenzitrone** [comment]
ESLint is JavaScript only
i would prefer a language agnostic solution

**Comment by Tyriar** [comment]
Since this one doesn't contribute and format on save yet it would complicate the extension more than it needs to be.
