### ISSUE TITLE
Feature request: When sorting plain-object properties, clean up the comma issue

### ISSUE THREAD

**Issue by estaylorco** [Tyriar/vscode-sort-lines#13]
Thank you for a simple but awesome extension!

I just noticed that when I sort the properties on a plain object, if the last object (which does not have a comma at the end of it) winds up in the middle, a comma isn't inserted.  Likewise, if a property located in the middle winds up at the end after the sort, the comma isn't removed.

Consider the following:

```
{
   xyz: 'xyz',
   abc: 'abc',
   def: 'def'
}
```

should become

```
{
   abc: 'abc',
   def: 'def',
   xyz: 'xyz'
}
```

As it stands now, after sorting, we have

```
{
   abc: 'abc',
   def: 'def' /* <= missing comma */
   xyz: 'xyz', /* <= comma not removed */
}
```

Would it be possible to fix this?

Thank you.

**Comment by Tyriar** [comment]
This is outside of the scope of this extensions and probably belongs more in a language extension that understands things about the text being sorted.
