### ISSUE TITLE
When will it be updated on the Marketplace?

### ISSUE THREAD

**Issue by jojorne** [Tyriar/vscode-sort-lines#130]
I don't know how or if it's possible to install extensions directly from GitHub. The thing is - a feature I use quite a lot was added some time ago - so I was wondering when it will be updated on the Marketplace.

**Comment by Tyriar** [comment]
@jojorne is https://github.com/Tyriar/vscode-sort-lines/pull/124 what you're after? That's the only change since the last release in July.

**Comment by Tyriar** [comment]
@jojorne I'll try publish it some time next week, busy with prepping/testing the next vscode release atm.
