### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Vincentzc** [Tyriar/vscode-sort-lines#14]
Before vs code, I use sublime text. So I hope this plugins works as sublime do.

**Comment by Tyriar** [comment]
Please elaborate on what you're after exactly.

**Comment by Vincentzc** [comment]
Sorry ,since I am not familiar with github,I press ctrl+enter. 
1. I can sort current file without select any line.  2. when I execute unique, I don't expect a sort at the same time.
