### ISSUE TITLE
full lines selection gets extra line sorted

### ISSUE THREAD

**Issue by agreppin** [Tyriar/vscode-sort-lines#15]
Having only 2 lines selected, 3 gets sorted:
![image](https://user-images.githubusercontent.com/26579013/29683607-3ccc5a8e-890f-11e7-8987-5b8fac630702.png)

My current workaround is to select lines upward, not downward.

**Comment by jcw-** [comment]
FYI, my understanding is that this is considered to be three selected lines - make that same selection in pretty much any editor and hit Tab and observe all three lines get shifted over.

**Comment by Tyriar** [comment]
Yes this is as designed since the selection does span 3 lines
