### ISSUE TITLE
Sort lines by column

### ISSUE THREAD

**Issue by rodlimao** [Tyriar/vscode-sort-lines#17]
Hi, there is a way to sort lines by a specific column? This is can be a feature?

If I sort line by default, I get:
>var xC as chr
>var yA as log
>var zB as int

I figure if I can do somthing like this:

sorted by 5th column
>var yA as log
>var zB as int
>var xC as chr

sorted by 9th column
>var xC as chr
>var zB as int
>var yA as log

Sorry about my english! I'm from Brazil.

**Comment by Tyriar** [comment]
I think the useful of this is limited and as such it's beyond the scope of the extension.
