### ISSUE TITLE
Conflict with default debug

### ISSUE THREAD

**Issue by cnavarro16** [Tyriar/vscode-sort-lines#22]
I've found that the default shortcut for sort lines (F9) conflicts with the default shortcut for toggling breakpoints in the vs code debugger (also F9). For some time I thought that the shortcut was broken after I upgraded to VS Code 1.19, but a search of the keybindings led me to this:

![image](https://user-images.githubusercontent.com/15855433/34086080-1755de36-e3ed-11e7-8619-bb950c03f81d.png)

I changed the setting on so all is good on my end. Don't know if you want to consider changing the default keybinding for this extension considering it clashes with the default set by microsoft in vscode? Thanks!

**Comment by Tyriar** [comment]
Many people would be relying on the extension keybinding at this point, I made F9 the default as that was the keybinding I think on Sublime that I used to use. My newer extensions generally leave everything unbound but I'm not sure that would be better than just leaving it as is.

**Comment by cnavarro16** [comment]
I understand where you're coming from. I mainly meant to raise this issue
to bring the conflict to your attention as this would likely impact anyone
who relies on the debugging features of vs code and uses the sort lines
extension. Now that I know I will just make the configuration change to fix
the conflict. Don't know if an alternative is to just have some sort of
note in the documentation that shows that the shortcut might conflict with
the toggle breakpoint one? Anyway, I'll leave it in your hands. Thanks for
your quick respose!

**Comment by Tyriar** [comment]
Thanks I made a comment in the readme, will wait for more changes to publish though.

**Comment by cnavarro16** [comment]
Awesome! Thanks for taking that feedback on board!
