### ISSUE TITLE
Organized in jumble, not alpabetical

### ISSUE THREAD

**Issue by BMCwebdev** [Tyriar/vscode-sort-lines#28]
Hi there. So this seems not to be working for me lately.
In a scss file, with this sample:
```
.rewardsButton{
  align-self: auto;
  position: relative;
  font-size: 14px;
  margin-bottom: 7px;
  margin-right: 7px;
 }
```
rearranges to:
```
.rewardsButton{
  margin-right: 7px;
  align-self: auto;
  font-size: 14px;
  margin-bottom: 7px;
  position: relative;
 }
```
Side note, would be nice to be able to select the entire code, including class name and brackets, otherwise:
```
  margin-right: 7px;
  align-self: auto;
  font-size: 14px;
  margin-bottom: 7px;
  position: relative;
 }
.rewardsButton{
```
Let me know if you need any other info. Running latest VSCode. Windows 7.

**Comment by Tyriar** [comment]
Which command are you running to sort?
