### ISSUE TITLE
Sort Lines downloads test folder. Package is 274MB. although code is only a few hundred KB.

### ISSUE THREAD

**Issue by SoftwareApe** [Tyriar/vscode-sort-lines#34]
![grafik](https://user-images.githubusercontent.com/17566442/38934878-1d897f26-431d-11e8-854d-8e330e3854a7.png)

I ran into the same issue with my own plugin. You need to change not the .gitignore but the .vscodeignore file to ignore this folder. It contains test data.

Just add ".vscode-test" to your .vscodeignore and it should be fine.

**Comment by Tyriar** [comment]
@SoftwareApe thanks for the report!

**Comment by Tyriar** [comment]
Published 1.6.1

**Comment by SoftwareApe** [comment]
That was so quick, thank you!
