### ISSUE TITLE
Sort entire file if no text is selected

### ISSUE THREAD

**Issue by garyking** [Tyriar/vscode-sort-lines#36]
If no text is selected, then please sort the entire file, when a command is run.

**Comment by hho** [comment]
Hi @Tyriar – it's been over 2 Months since this has been merged. Any chance that we get a new release pushed out?

**Comment by Tyriar** [comment]
@hho thanks for the ping, I'll release it now 👍

**Comment by Tyriar** [comment]
Just published 1.8.0

**Comment by hho** [comment]
Thanks! Got it and it works 😎
