### ISSUE TITLE
Accented letters are put at end when sorting

### ISSUE THREAD

**Issue by jansensan** [Tyriar/vscode-sort-lines#38]
- VSCode Version: Version 1.25.1 (1.25.1)
- OS Version: OSX Yosmite 10.10.5

Steps to Reproduce:

1. Have unsorted letters, a mix of accented and non-accented. In this example, I'm using most French accented letters, which are only vowels. There are other languages with different or more accented letters.

ex.:
```
a
b
c
e
f
g
d
l
j
k
è
w
ù
à
ê
ë
ô
é
i
h
ö
m
n
s
o
q
p
r
z
u
v
t
x
ï
y
```

2. Select text, use CMD+SHIFT+P and select `Sort lines (case sensitive)`

3. Accented letters are put at the total end of the sorting:

```
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
à
è
é
ê
ë
ï
ô
ö
ù
```

Expected: as per language rules—written language I mean, not any development language—the alphabetical sorting should have the accented letters next to the non-accented ones: 

```
a
à
b
c
d
e
è
é
ê
ë
f
g
h
i
ï
j
k
l
m
n
o
ô
ö
p
q
r
s
t
u
ù
v
w
x
y
z
```

As far as I know, operating systems handle this sorting properly. Using VSCode's sorting doesn't have that issue, only the methods added by this plugin—which is otherwise quite good.

**Comment by Tyriar** [comment]
The `Sort lines (Natural)` is locale aware and works as expected.
