### ISSUE TITLE
natural sort bug: doesn't handle negative numbers

### ISSUE THREAD

**Issue by kobi2187** [Tyriar/vscode-sort-lines#41]
```
-1 = BelowNormal,
-2 = Lowest,
-15 = Idle,  
0 = Normal,  
1 = AboveNormal,  
2 = Highest,  
15 = TimeCritical,  
```
the comparison function is not right. -15 should come before -2 and -1
it looks like a regular positive sort, disregarding the - sign.

**Comment by Tyriar** [comment]
I'm not sure "natural sort" is meant to work with negative numbers, I did a quick search and couldn't find any implementations that supported this? Let me know if you find some document which describes this
