### ISSUE TITLE
Request: stable sort algorithm

### ISSUE THREAD

**Issue by benfletcher** [Tyriar/vscode-sort-lines#46]
Could the sort algorithm used be changed to one that is a [stable sort](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability), i.e., the order of equal items remain unchanged relative to each other.

I have a list of items that I sort alphabetically and then by length with the goal of the items remaining sorted alphabetically (within each length group) after the length sort.

Here's a test "file" on which the sort changes the orders of existing items when doing the sort by line length:

```txt
back
band
blah
buck
burp
deck
drill
duck
grand
hello
help
puck
quill
trill
zebra
```

Thanks for your work on this. I can of course manually select groups of line lengths instead of doing the whole file at once, if this turns out to be a difficult issue or results in worse performance.

Edit: Digging in a bit more, it looks like chromium only recently switched to a stable sort (in >=70 according to [this stackoverflow answer](https://stackoverflow.com/a/3027715)). So probably best to just wait for vscode's electron engine to get up to that version? Manually implementing a stable sort really doesn't seem worth it in this light.

Also, FWIW, it already is stable for lines counts less than 10.

**Comment by AnneTheAgile** [comment]
fyi 
https://github.com/sgryjp/vscode-stable-sort
https://marketplace.visualstudio.com/items?itemName=sgryjp.vscode-stable-sort&ssr=false#overview
