### ISSUE TITLE
Feature request: Horizontal sort

### ISSUE THREAD

**Issue by pcjmfranken** [Tyriar/vscode-sort-lines#47]
Could be extremely handy in one line imports or destructuring.

```js
import { vuur, mies, aap, duif } from '../some-file'
```

```js
const { zus, hok, does, weide, teun } = obj
```

**Comment by Tyriar** [comment]
I think this is a little out of the scope of this extension, it would be a good separate extension or as part of a language-specific one.

**Comment by dianjuar** [comment]
I would like to have this feature.
In javascript when you import a lot of stuff from a module you have everything in a line like 

```ts
import { Component, OnDestroy, OnInit, ViewChild, ElementRef } from '@angular/core';
```

Would be nice if you can select the imports and sort them
