### ISSUE TITLE
Sort sizes

### ISSUE THREAD

**Issue by dufferzafar** [Tyriar/vscode-sort-lines#48]
Suppose you have a list of values that have sizes:

```text
932.8KB
659.9KB
1.5MB
1.1MB
945.5KB
854.6KB
989.5KB
802.9KB
```

I currently sort this using the "EditWithShell" VSCode extension (by piping the data to Unix `sort -rh`) but it'd be nice to have this builtin this extension itself.

**Comment by Tyriar** [comment]
duplicate of https://github.com/Tyriar/vscode-sort-lines/issues/40
