### ISSUE TITLE
Request: Reverse

### ISSUE THREAD

**Issue by tmdag** [Tyriar/vscode-sort-lines#49]
simple reverse (from last to first) selected lines would be useful.

**Comment by Tyriar** [comment]
I think this is out of the scope of this extension, it could be its own though.

**Comment by tmdag** [comment]
What I had in mind sounds very much in the same scope as you already have different modes of sorting based on its context. What I was after just a simplest version of sorting - not based on context, just based on line order :)
"sort lines" extension having sort lines in reverse order sounds like a scope of it :)

**Comment by Tyriar** [comment]
Oh I misunderstood, I thought you wanted the reverse character within a single line. So you're after flipping lines around without caring about the content of them?

**Comment by WretchedDade** [comment]
Has this been implemented yet? If not, I can pick it up!

**Comment by Tyriar** [comment]
@WretchedDade sure, I think we're after just a `Sort Lines: Reverse Lines` command which will just flip the lines around.

**Comment by adamprocter** [comment]
I would also like this please. to replace this and keep me in VSCode - https://gillmeister-software.com/online-tools/text/reverse-sort-list.aspx

**Comment by matthias-ccri** [comment]
I also needed this today. I was sorting lines with numbers, and I did a natural sort, but the result placed the large numbers at the bottom. AFAIK, it appears there is no "natural sort, descending" action, only "natural sort".

To be clear, I'm not asking for that action to be added. I don't want to choose between 20 actions permutations. I can just sort the lines, then reverse it. You know, Missy Elliot style.

**Comment by mrienstra** [comment]
FYI, [Text Power Tools](https://marketplace.visualstudio.com/items?itemName=qcz.text-power-tools) has a "Reverse lines" command, added in [1.30.0](https://github.com/qcz/vscode-text-power-tools/commit/93afc12).

**Comment by Tyriar** [comment]
I think I'll call this out of scope again since text power tools handles this with many text manipulation commands.
