### ISSUE TITLE
Ordering alfabetically, ascending, case insensitive gives different result?

### ISSUE THREAD

**Issue by fmaiabatista** [Tyriar/vscode-sort-lines#50]
Hi, first of all I'd like to thank for the extension! It's been really helpful.

But I'd like to report an inconsistency I noticed when using the alfabetical, ascending, case insensitive sort option.

![image](https://user-images.githubusercontent.com/1574224/62481547-11e2f580-b789-11e9-87fd-a9467864f58e.png)

The image above shows that "FETCH_TREND" at line 26 is sorted before "FETCH_TREND_VARIABLE" at line 27, which was expected.

But then on class Fedx the sort order is switched, resulting in "FETCH_TREND" (line 46) coming after "FETCH_TREND_VARIABLE" (line 45).

Is this somehow expected? Is there something I'm not seeing there?

**Comment by Tyriar** [comment]
Working as designed because that's what localeCompare does:

![image](https://user-images.githubusercontent.com/2193314/62643347-a1f57c00-b8fc-11e9-95c9-b0b52709afb5.png)
