### ISSUE TITLE
Sort on rectangular selection / Sort within rectangular selection (enhancement request)

### ISSUE THREAD

**Issue by northwestfrog** [Tyriar/vscode-sort-lines#54]
Hi,

Let me start off by thanking you for the sort feature you are providing. It is extremely useful.

I was wondering if it would be possible to sort whole lines based on the rectangular selection as being the sort key?

Also, based on a rectangular selection, if was possible to sort the content of the rectangular selection exclusively (sort within rectangular selection)?

Thanks

**Comment by Tyriar** [comment]
I think that might be better done in a separate extension that focused on that experience. Closing as out of scope
