### ISSUE TITLE
Add a "remove duplicated line" feature into?

### ISSUE THREAD

**Issue by Tairraos** [Tyriar/vscode-sort-lines#55]
will you consider add a "remove duplicated line" feature into? thanks.

**Comment by Tyriar** [comment]
Sure, a new command "Sort Lines: Remove duplicate lines" should work. Open to PRs

**Comment by merelj** [comment]
i'd like to take this issue if you don't mind

**Comment by Tyriar** [comment]
@merelj sounds good 👍

**Comment by 183amir** [comment]
This is a great feature but the name is confusing because it says `Sort Lines (remove duplicate lines)`. It sounds like that it will sort the lines as well. Maybe, you could add a comment about this command in the readme?

**Comment by Tairraos** [comment]
![image](https://user-images.githubusercontent.com/185069/97510262-53c80f00-19bf-11eb-8517-50e12e148935.png)
FYI, the textmate has this feature and here is the contex menu.

**Comment by Tyriar** [comment]
@183amir good feedback, created https://github.com/Tyriar/vscode-sort-lines/issues/85. Closing this as it's merged.
