### ISSUE TITLE
Sorting things

### ISSUE THREAD

**Issue by sjoshid** [Tyriar/vscode-sort-lines#58]
Just out of curiosity what is the expected behavior when a selection contains multiple things? Like chars, letters, tabs, etc. I can install the plugin and try it out myself....but as a text editor plugin I want to know if some thought was given to this.. and what decision were made.

**Comment by Tyriar** [comment]
The code itself is very simple and installing it is very easy so you should be able to figure out whether it works for you yourself. If you feel there's a hole in the documentation I'm open to PRs.
