### ISSUE TITLE
Consider adding a menu option

### ISSUE THREAD

**Issue by jansensan** [Tyriar/vscode-sort-lines#6]
While the functionality of this feature is quite correct and useful, it expects the user to always memorize the keyboard shortcut and also on the consideration that F* keys are used by all.

In order to improve the accessibility of this feature, is it possible to consider an addition of an actual menu in the application? Is this available to extensions developers? Otherwise, this feels like a mystery meat and is impossible to use if one forgets what are the exact keys to use.

Thanks for the consideration you can give to this request.

**Comment by Tyriar** [comment]
VS Code doesn't expose an API to add to the menu bar unfortunately. The readme explains how to install and use the extension, namely all its functionality is available through the command palette.

**Comment by TerraTech** [comment]
@Tyriar Perhaps this can be revisited in light of:
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus
