### ISSUE TITLE
End of file gets wrapped up in sort

### ISSUE THREAD

**Issue by chaim1221** [Tyriar/vscode-sort-lines#71]
`\n` is the EOF character in *NIX derivatives; see e.g.

https://www.gnu.org/software/libc/manual/html_mono/libc.html#EOF-and-Errors
https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf

When I select a block of text ending with `\n` using this plugin, and sort it, the `\n` that is EOF winds up at the beginning of the block of text.

The same happens when I sort the whole file.

In these cases the `\n` that represents EOF is removed and the file is no longer a valid file.

One solution would be to verify if the `\n` at the end of a selection (including "the entire file" as a selection) is indeed the EOF, and excluding it from the result set.

**Comment by Tyriar** [comment]
This is by design, hit shift+right instead of shift+down to you don't select the last `\n`. On ensuring `\n` remains there, you can you lint/format tools or editorconfig to enforce this kind of thing on save.
