### ISSUE TITLE
[Future request] Show how many lines are selected for sorting

### ISSUE THREAD

**Issue by kanlukasz** [Tyriar/vscode-sort-lines#72]
I'm afraid it can be out of the scope of this extension, but maybe no 🤷‍♂

I think it can be useful if your extension will show **how many lines are selected for sorting**. Maybe in the status bar.

**Example:**
![obraz](https://user-images.githubusercontent.com/30685349/73426790-8613e580-4335-11ea-91bf-1f1bf4ebbd2c.png)

Sorry for no PR but i'm just a PHP Dev 😿

**Comment by Tyriar** [comment]
Yep out of scope. This doesn't have anything to do with sorting so it would make a good stand alone extension if it's useful to you.
