### ISSUE TITLE
Feature request: sort lines by symbol/property name (and allow brackets, etc)

### ISSUE THREAD

**Issue by qimingweng** [Tyriar/vscode-sort-lines#77]
Suppose you have a Javascript file that looks like this.

```js
const a = {
  a: 'a',
  b: 'b',
  c: {
    hello: 'world',
  },
};
```

Is it possible to sort the properties without sorting each line uniquely? Perhaps we can read from characters like {, (, until they all resolve with }, ).

I'm also having a hard time articulating this type of sort using English words, so maybe there's another library or term for this and would be grateful if you could help me define this better.

**Comment by Tyriar** [comment]
This sort of thing I've always considered out of scope for this extension since it needs language smarts, trying to cover lots of language constructs without a proper parser seems like we would be setting out for failure.
