### ISSUE TITLE
Sort by numbers

### ISSUE THREAD

**Issue by KimeT** [Tyriar/vscode-sort-lines#8]
Hello, sorting by numbers would be a nice feature, for example in sorting of lines containing only numbers or using markdown ordered (numbered) lists. If you sort lines "normally" (using F9), the lines get ordered in alphabetical order like this:
```
1. sdfg
11. sdbsd
11111. sdfbd
2. sdfbadf
21. sdfdfg
34. sddasfg
4. sdfsag
5. asdfgsdfg
```

Sorting by numbers would result in list like this:
```
1. sdfg
2. sdfbadf
4. sdfsag
5. asdfgsdfg
11. sdbsd
21. sdfdfg
34. sddasfg
11111. sdfbd
```

So, this sort by number could work followingly:
If line starts with numbers, read line until the next non-number or line ending. Then sort these lines in numerical order by numbers detected in line beginning. If line starts with a non-number, then sort these lines alphabetically (after number lines).

**Comment by sergeevabc** [comment]
Err… Hello?
