### ISSUE TITLE
Feature request: When sorting nested objects, maintain the integrity of the nested object

### ISSUE THREAD

**Issue by michaelaflores** [Tyriar/vscode-sort-lines#82]
When sorting an object that contains objects inside of it, it would be great if it were at least treated as a single entity to be moved around. I realize this extension's scope may not extend to understanding language semantics but just in case, thought I'd ask :)

Example:
```ts
type ScreenCaptureProps = {
  active: string;
  icon: React.ReactElement;
  style: {
    svg: CSSType.Properties
  };
  onClick: () => any;
  variant: "pill" | "rounded" | "custom";
  label: string;
}
```

Gets sorted as 
```ts
type ScreenCaptureProps = {
    svg: CSSType.Properties
  };
  active: string;
  icon: React.ReactElement;
  label: string;
  onClick: () => any;
  style: {
  variant: "pill" | "rounded" | "custom";
}
```

**Comment by Tyriar** [comment]
To do this correctly we would need this extension to understand TypeScript which is definitely out of scope.
