### ISSUE TITLE
Publish extension to open-vsx.org

### ISSUE THREAD

**Issue by sebthom** [Tyriar/vscode-sort-lines#92]
Please submit your extension to the [Open VSX](https://open-vsx.org/) registry/marketplace.

This way it can be legally downloaded/installed in opensource builds/forks of VSCode, e.g. VSCodium and Eclipse [Theia](https://theia-ide.org/).

FAQs: https://www.eclipse.org/legal/open-vsx-registry-faq/

Thanks!

**Comment by Tyriar** [comment]
I don't have any plans to do this as I don't use those offerings and don't want to deal with their maintenance burden. Since the repo is MIT, nothing is stopping someone from publishing it though afaik.
